version: '3.8'
services:
  sircon-bot: &sircon-bot
    build: .
    env_file:
      - .env.development
    volumes:
      - .:/usr/sircon-bot
    ports:
      - 4000:4000
    depends_on:
      - db
    stdin_open: true

  db:
    image: mongo:4.0-xenial
    command: mongod --smallfiles --quiet
    volumes:
      - .:/mongo/db
    ports:
      - 27017:27017
